---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ .Release.Name }}-pod-launcher-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "airflow.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-pod-launcher-role
subjects:
  - kind: ServiceAccount
    name: {{ include "airflow.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"