---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.fullname" . }}
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ default 8080 .Values.airflow.webserver.service.port }}
      targetPort: {{ default 8080 .Values.airflow.webserver.service.port }}
  selector:
    {{- include "webserver.selectorLabels" . | nindent 4 }}