---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-common
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  airflow-username: "{{ .Values.airflow.webserver.defaultUser.username }}"
  airflow-password: "{{ .Values.airflow.webserver.defaultUser.password }}"
  airflow-fernet-key: "{{ .Values.airflow.fernetKey }}"
  webserver-secret-key: "{{ .Values.airflow.webserver.secretKey }}"