---
{{- if .Values.postgresql.enabled }}
{{- $dbHost :=  .Values.postgresql.host | default (printf "%s-%s-%s" .Release.Name ( include "app.name" . ) "postgresql") }}
{{- $dbPort :=  toString .Values.postgresql.port | default "5432" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{ include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection: "{{ urlJoin (dict "scheme" (printf "%s" .Values.postgresql.type) "userinfo" (printf "%s:%s" .Values.postgresql.auth.userName  .Values.postgresql.auth.userPassword) "host" (printf "%s:%s" $dbHost $dbPort ) "path" (printf "/%s" .Values.postgresql.database)) }}"
  adminPassword: "{{ .Values.postgresql.auth.adminPassword }}"
  userName: "{{ .Values.postgresql.auth.userName }}"
  userPassword: "{{ .Values.postgresql.auth.userPassword }}"
  database: "{{ .Values.postgresql.database}}"
{{ end }}