---
{{ if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{ include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection: {{ printf "redis://:%s@%s:%s" .Values.redis.auth.password (include "redis.fullname" . ) (.Values.redis.port | toString) }}
  password: {{ .Values.redis.auth.password }}
{{ end }}